//
//  DetailModels.swift
//  Demo_api_proccessing
//
//  Created by Khoa Nguyen on 2/25/20.
//  Copyright (c) 2020 Khoa Nguyen. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Detail
{
  // MARK: Use cases
  
  enum Something
  {
    struct Request
    {
    }
    struct Response
    {
    }
    struct ViewModel
    {
    }
  }
}
